AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*'

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Rails/HasAndBelongsToMany:
  Enabled: false
