language: ruby

rvm:
  - "2.2.3"

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database TuConstituyes_test;' -U postgres

script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
