# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3385945966c3b21fe12e6192ccec3890febad960c581dc806559987c4788eacba7b5700ef94d20b09b61c101d73bacf01aea441a1308caf325eac20a08bed22

test:
  secret_key_base: 92e2f3be86dfb41b441f8350a491b6ea852c8c54cd792ffc481c89dbdf16557cfcf428fd909c48c4baa160f037cb89c2b6f02ef2ac72ef7259a91ee83ce2b305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
